
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async startWatch(repoRoot: string, channel: TAURI_CHANNEL<FileEventBatch>) : Promise<Result<Worktree[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_watch", { repoRoot, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopWatch() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_watch") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorktrees(repoRoot: string) : Promise<Result<Worktree[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_worktrees", { repoRoot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the file tree index from the active watch for the Phase 4 radar spatial map.
 * Returns an empty vec if no watch is active.
 * 
 * Paths are serialized as repo-relative with forward-slash separators. Storing
 * absolute paths on the frontend created an O(depth) chain of single-child
 * directory wrappers (`/`, `home`, `prannayag`, …) before any real content,
 * which visually crushed the treemap into a corner. The repo root itself is
 * emitted as `""` so the frontend root aggregate stays intact.
 */
async getTreeIndex() : Promise<Result<TreeIndexEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tree_index") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the dependency graph (in-repo import/use/mod edges) for the active watch.
 * Returns an empty vec if no watch is active.
 * 
 * Edges use repo-relative forward-slash paths (matching `get_tree_index` convention,
 * commit `a1b15b6`) so the frontend can join against `radarStore.contentionScores`
 * keys without a separate normalization layer.
 * 
 * CPU-heavy parsing runs on `tauri::async_runtime::spawn_blocking` so the main
 * async runtime stays responsive during the <2s build target (D-24).
 */
async getDependencyGraph() : Promise<Result<DependencyEdgeDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dependency_graph") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLaunchCwd() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_launch_cwd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectGitRoot(path: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_git_root", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async persistLastRepo(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("persist_last_repo", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLastRepo() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_last_repo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all currently tracked agents.
 */
async listAgents() : Promise<Result<AgentInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_agents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List adapter types whose launch binary resolves on PATH.
 * 
 * Used by the Deploy dialog to hide agent types that aren't installed,
 * so users can't select launches that are guaranteed to fail.
 */
async listAvailableAgentTypes() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_available_agent_types") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Launch a new agent of the given type in the specified working directory.
 * 
 * T-03-05 mitigations:
 * - Validates cwd exists and is a directory.
 * - Only launches binaries matched by registered adapters (no arbitrary PATH exec).
 */
async launchAgent(agentType: string, cwd: string, intent: string | null, options: LaunchOptions | null) : Promise<Result<AgentInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_agent", { agentType, cwd, intent, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Terminate a running agent by ID.
 * 
 * T-03-06 mitigation: Only terminates processes tracked in the registry.
 * Will not kill arbitrary PIDs.
 */
async terminateAgent(agentId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminate_agent", { agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update an agent's intent/task description (manual labeling per D-08 fallback).
 */
async updateAgentIntent(agentId: string, intent: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_agent_intent", { agentId, intent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the stdout log buffer for an agent.
 * 
 * T-03-08: accepted risk -- logs are local process output.
 */
async getAgentLogs(agentId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_agent_logs", { agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: get current notification preferences.
 */
async getNotificationPrefs() : Promise<Result<NotificationPrefs, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_notification_prefs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: update notification preferences.
 */
async updateNotificationPrefs(prefs: NotificationPrefs) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_notification_prefs", { prefs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all active (non-dismissed) conflict alerts.
 */
async listConflicts() : Promise<Result<ConflictAlert[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_conflicts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismiss a conflict alert by its ID.
 */
async dismissConflict(conflictId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_conflict", { conflictId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current conflict detection window in milliseconds.
 */
async getConflictSettings() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conflict_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update the conflict detection window. Validates range: 1000-60000ms (1-60 seconds).
 * 
 * Mitigates T-03-09: prevents DoS via 0ms window (every write conflicts) or
 * effectiveness bypass via huge window.
 */
async updateConflictWindow(windowMs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_conflict_window", { windowMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all approval requests, newest first.
 */
async listApprovalRequests() : Promise<Result<ApprovalRequest[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_approval_requests") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Approve a pending request.
 */
async approveRequest(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("approve_request", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deny a pending request.
 */
async denyRequest(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("deny_request", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Request more information on a pending request. Also creates a chat message
 * with the question so the agent sees it in the communications channel.
 */
async askMoreInfo(id: number, question: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ask_more_info", { id, question }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Approve a request with edited content.
 */
async approveWithEdits(id: number, editedContent: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("approve_with_edits", { id, editedContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a chat message to an agent.
 */
async sendChatMessage(agentId: string, content: string) : Promise<Result<ChatMessage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_chat_message", { agentId, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all chat messages for a given agent, oldest first.
 */
async listChatMessages(agentId: string) : Promise<Result<ChatMessage[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_chat_messages", { agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update the delivery status of a chat message.
 * Validates that status is one of 'delivered', 'queued', 'unsupported'.
 */
async updateMessageDeliveryStatus(messageId: number, status: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_message_delivery_status", { messageId, status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all configured protected path glob patterns.
 */
async listProtectedPaths() : Promise<Result<ProtectedPath[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_protected_paths") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a new protected path glob pattern.
 */
async addProtectedPath(globPattern: string) : Promise<Result<ProtectedPath, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_protected_path", { globPattern }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a protected path by ID.
 */
async removeProtectedPath(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_protected_path", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: get current CPU and memory usage.
 * 
 * Reuses the System instance from managed state. The frontend's 2-second
 * polling interval provides the time delta needed for meaningful CPU
 * usage values between refresh calls.
 */
async getSystemLoad() : Promise<Result<SystemLoadInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_system_load") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read file versions for a conflict: base from git HEAD, current from disk.
 * 
 * Both agent_a_content and agent_b_content are set to the current disk content
 * since agents write to the same file -- the latest write is what's on disk.
 * The base version comes from `git show HEAD:<relative_path>`.
 * 
 * File size is capped at 1MB (T-05-04).
 */
async readConflictFiles(conflictId: string) : Promise<Result<ConflictFileVersions, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_conflict_files", { conflictId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apply a conflict resolution: backup files, write merged content, persist to DB.
 * 
 * Steps:
 * 1. Look up conflict alert
 * 2. Read current file + git base
 * 3. Save backups (base, agent_a, agent_b versions)
 * 4. Write merged_content to disk
 * 5. Save backup of merged version
 * 6. INSERT into conflict_resolutions
 * 7. UPDATE conflict_events SET resolution_id
 * 8. Dismiss the conflict alert
 * 9. Emit "conflict-resolved" event
 * 10. Return the ResolutionRecord
 */
async applyResolution(conflictId: string, mergedContent: string, hunkResolutions: HunkResolution[], resolutionType: string) : Promise<Result<ResolutionRecord, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_resolution", { conflictId, mergedContent, hunkResolutions, resolutionType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all conflict resolutions, most recent first.
 */
async listConflictResolutions() : Promise<Result<ResolutionRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_conflict_resolutions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List files touched in a given session, ordered by write count descending.
 */
async listSessionFiles(sessionId: number) : Promise<Result<SessionFileRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_session_files", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record a file write for a session (upsert pattern).
 * 
 * If the file was already recorded for this session, increments write_count.
 * Also updates the session's file_count aggregate.
 */
async recordSessionFile(sessionId: number, filePath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_session_file", { sessionId, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all agent sessions with file counts, most recent first.
 */
async listSessions() : Promise<Result<SessionRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List approval request history with agent context, most recent first.
 */
async listApprovalHistory() : Promise<Result<ApprovalHistoryRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_approval_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Metadata about an agent visible to the frontend and stored in the registry.
 */
export type AgentInfo = { id: string; agentType: string; protocol: string; state: AgentState; pid: number | null; cwd: string | null; intent: string | null }
/**
 * Agent lifecycle state machine.
 * 
 * Valid transitions (per 03-RESEARCH.md):
 * - Running -> Idle, Waiting, Conflict, Error
 * - Idle -> Running, Error
 * - Waiting -> Running, Error
 * - Conflict -> Running, Error
 * - Error -> Running
 */
export type AgentState = "running" | "idle" | "waiting" | "conflict" | "error"
/**
 * An approval request record for history display.
 */
export type ApprovalHistoryRecord = { id: number; sessionId: number | null; agentId: string | null; requestType: string; filePath: string | null; status: string; createdAt: string; resolvedAt: string | null; responseNote: string | null }
/**
 * An approval request from an agent (enriched with Phase 4 fields).
 */
export type ApprovalRequest = { id: number; agentId: string; requestType: string; filePath: string | null; diffContent: string | null; status: string; urgency: string; responseNote: string | null; editedContent: string | null; createdAt: string; resolvedAt: string | null }
/**
 * Which process we believe authored the file event.
 * 
 * Per D-05/D-06 this is best-effort. `Unattributed` is the common fallback
 * when sysinfo's process snapshot couldn't find an agent whose cwd contains
 * the event's path. `Ambiguous` carries every candidate PID so the UI can
 * surface the disambiguation rather than pick wrong.
 */
export type Attribution = { kind: "pid"; value: number } | { kind: "ambiguous"; value: number[] } | { kind: "unattributed" }
/**
 * A chat message between user and agent.
 */
export type ChatMessage = { id: number; agentId: string; direction: string; content: string; deliveryStatus: string; approvalRequestId: number | null; createdAt: string }
/**
 * An alert generated when two different agents write the same file within the
 * configured conflict window.
 */
export type ConflictAlert = { id: string; filePath: string; agentAId: string; agentAPid: number; agentBId: string; agentBPid: number; detectedAtMs: number; conflictWindowMs: number; hunkHintsA: [number, number] | null; hunkHintsB: [number, number] | null; dismissed: boolean }
/**
 * File versions for a conflict: base (git HEAD), and current disk content.
 */
export type ConflictFileVersions = { baseContent: string; agentAContent: string; agentBContent: string; filePath: string; agentAId: string; agentBId: string }
/**
 * Wire-format for the get_dependency_graph Tauri command (D-05).
 */
export type DependencyEdgeDto = { 
/**
 * Repo-relative forward-slash path of importing file.
 */
from: string; 
/**
 * Repo-relative forward-slash path of imported file.
 */
to: string; kind: EdgeKind }
export type EdgeKind = "import" | "reexport" | "typeOnly" | "dynamicImport" | "use" | "modDecl" | "fromImport" | "importStmt"
/**
 * A single debounced, attributed filesystem event.
 */
export type FileEvent = { path: string; kind: FileEventKind; 
/**
 * Unix timestamp in milliseconds (UTC). i64 rather than u64 to match the
 * `chrono::DateTime::timestamp_millis()` return type.
 */
timestampMs: number; attribution: Attribution }
/**
 * A batch of events sent across the IPC boundary in one payload.
 * 
 * Batching amortizes the serde + Channel overhead across many events. The
 * `dropped_batches` counter is how the Rust side signals back-pressure to the
 * frontend: when the bounded tokio mpsc between the watcher and the sender
 * actor is full, whole batches are dropped and this counter increments.
 */
export type FileEventBatch = { events: FileEvent[]; batchId: number; droppedBatches: number }
/**
 * The kind of filesystem mutation observed.
 * 
 * Writes-only per D-11 — no read events. Rename carries both source and
 * destination paths so consumers don't need to correlate a separate
 * Remove+Create pair (the debouncer already does that work).
 */
export type FileEventKind = { kind: "create" } | { kind: "modify" } | { kind: "remove" } | { kind: "rename"; from: string; to: string }
/**
 * Resolution choice for a single hunk in the merge UI.
 */
export type HunkResolution = { hunkIndex: number; choice: string; customContent: string | null }
/**
 * Adapter-specific launch tuning. Currently only Claude Code consumes any of
 * these; other adapters ignore them. Kept as one serializable struct so the
 * IPC surface stays flat even as new options show up.
 */
export type LaunchOptions = { 
/**
 * Claude Code: adds `--permission-mode acceptEdits` so file-edit tools
 * run without prompting.
 */
acceptEdits: boolean; 
/**
 * Claude Code: adds `--dangerously-skip-permissions` which disables the
 * permission prompt entirely. Takes precedence over `accept_edits`.
 */
dangerouslySkipPermissions: boolean }
/**
 * Per-state notification preferences.
 * 
 * Each field controls whether a transition TO that state triggers a
 * native OS notification.
 */
export type NotificationPrefs = { 
/**
 * Notify when agent enters Running state. Default: false.
 */
onRunning: boolean; 
/**
 * Notify when agent enters Idle state. Default: true.
 */
onIdle: boolean; 
/**
 * Notify when agent enters Waiting state. Default: true.
 */
onWaiting: boolean; 
/**
 * Notify when agent enters Conflict state. Default: true.
 */
onConflict: boolean; 
/**
 * Notify when agent enters Error state. Default: true.
 */
onError: boolean }
/**
 * Frontend-facing process info (serializable via specta).
 * 
 * `parent_pid` is serialized as `parentPid` by the camelCase rename rule.
 */
export type ProcessInfo = { pid: number; name: string; cwd: string | null; exe: string | null; parentPid: number | null }
/**
 * A protected path glob pattern that triggers synthetic approval requests.
 */
export type ProtectedPath = { id: number; globPattern: string; createdAt: string }
/**
 * A persisted conflict resolution record.
 */
export type ResolutionRecord = { id: number; conflictEventId: number | null; filePath: string; agentAId: string; agentBId: string; resolutionType: string; hunkResolutions: string; notificationStatus: string; resolvedAt: string }
/**
 * A file record within a session.
 */
export type SessionFileRecord = { id: number; sessionId: number; filePath: string; writeCount: number; lastWrittenAt: string }
/**
 * An agent session record for history display.
 */
export type SessionRecord = { id: number; agentId: string; agentType: string; status: string; startedAt: string; endedAt: string | null; fileCount: number }
/**
 * Live system load snapshot.
 */
export type SystemLoadInfo = { cpuPercent: number; memoryPercent: number }
export type TAURI_CHANNEL<TSend> = null
/**
 * Serializable tree node for frontend consumption (VIZN-01, VIZN-05).
 */
export type TreeIndexEntry = { path: string; size: number; isDir: boolean; depth: number }
export type Worktree = { path: string; head: string | null; branch: string | null; isMain: boolean; isBare: boolean; detached: boolean; locked: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
