// This file was generated by [tauri-specta](https://github.com/specta-rs/tauri-specta).
// Do not edit this file manually.

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE } from "@tauri-apps/api/core";
import type { InvokeArgs } from "@tauri-apps/api/core";

// Wrapper to provide type-safe invoke
const invoke = TAURI_INVOKE as <T>(cmd: string, args?: InvokeArgs) => Promise<T>;

/** user-defined commands **/

export const commands = {
  async startWatch(repoRoot: string, channel: TAURI_CHANNEL<FileEventBatch>) {
    return invoke<Worktree[]>("start_watch", { repoRoot, channel });
  },
  async stopWatch() {
    return invoke<null>("stop_watch");
  },
  async listWorktrees(repoRoot: string) {
    return invoke<Worktree[]>("list_worktrees", { repoRoot });
  },
};

/** user-defined types **/

export type FileEventKind =
  | { kind: "create" }
  | { kind: "modify" }
  | { kind: "remove" }
  | { kind: "rename"; from: string; to: string };

export type Attribution =
  | { kind: "pid"; value: number }
  | { kind: "ambiguous"; value: number[] }
  | { kind: "unattributed" };

export type FileEvent = {
  path: string;
  kind: FileEventKind;
  timestampMs: number;
  attribution: Attribution;
};

export type FileEventBatch = {
  events: FileEvent[];
  batchId: number;
  droppedBatches: number;
};

export type Worktree = {
  path: string;
  head: string | null;
  branch: string | null;
  isMain: boolean;
  isBare: boolean;
  detached: boolean;
  locked: boolean;
};

export type ProcessInfo = {
  pid: number;
  name: string;
  cwd: string | null;
  exe: string | null;
  parentPid: number | null;
};

/** tauri-specta helpers -- TAURI_CHANNEL placeholder for Channel type **/
type TAURI_CHANNEL<T> = { onmessage: (response: T) => void };
