// @ts-nocheck
// specta emits unused TAURI_CHANNEL placeholder + __makeEvents__ helper that
// its own Channel<T> import then shadows; disable TS checks on this generated file.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async startWatch(repoRoot: string, channel: TAURI_CHANNEL<FileEventBatch>) : Promise<Result<Worktree[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_watch", { repoRoot, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopWatch() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_watch") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorktrees(repoRoot: string) : Promise<Result<Worktree[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_worktrees", { repoRoot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the file tree index from the active watch for the Phase 4 radar spatial map.
 * Returns an empty vec if no watch is active.
 * 
 * Paths are serialized as repo-relative with forward-slash separators. Storing
 * absolute paths on the frontend created an O(depth) chain of single-child
 * directory wrappers (`/`, `home`, `prannayag`, …) before any real content,
 * which visually crushed the treemap into a corner. The repo root itself is
 * emitted as `""` so the frontend root aggregate stays intact.
 */
async getTreeIndex() : Promise<Result<TreeIndexEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tree_index") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the dependency graph (in-repo import/use/mod edges) for the active watch.
 * Returns an empty vec if no watch is active.
 * 
 * Edges use repo-relative forward-slash paths (matching `get_tree_index` convention,
 * commit `a1b15b6`) so the frontend can join against `radarStore.contentionScores`
 * keys without a separate normalization layer.
 * 
 * CPU-heavy parsing runs on `tauri::async_runtime::spawn_blocking` so the main
 * async runtime stays responsive during the <2s build target (D-24).
 */
async getDependencyGraph() : Promise<Result<DependencyEdgeDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dependency_graph") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the IPC bridge surface (commands + handlers + callers) for the active
 * watch. Returns an empty vec if no watch is active.
 * 
 * Bridges use repo-relative forward-slash paths (matching `get_tree_index`
 * convention, commit `a1b15b6`).
 * 
 * CPU-heavy parsing runs on `tauri::async_runtime::spawn_blocking` so the main
 * async runtime stays responsive during the <100ms build target (D-35).
 */
async getIpcBridges() : Promise<Result<IpcBridgeDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ipc_bridges") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLaunchCwd() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_launch_cwd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectGitRoot(path: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_git_root", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async persistLastRepo(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("persist_last_repo", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLastRepo() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_last_repo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all currently tracked agents.
 */
async listAgents() : Promise<Result<AgentInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_agents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List adapter types whose launch binary resolves on PATH.
 * 
 * Used by the Deploy dialog to hide agent types that aren't installed,
 * so users can't select launches that are guaranteed to fail.
 */
async listAvailableAgentTypes() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_available_agent_types") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Launch a new agent of the given type in the specified working directory.
 * 
 * T-03-05 mitigations:
 * - Validates cwd exists and is a directory.
 * - Only launches binaries matched by registered adapters (no arbitrary PATH exec).
 * 
 * Phase 10 D-06 + D-12: branches on `adapter.capabilities().chat_duplex`.
 * Duplex adapters (claude-code) take the chat_runtime path — parser +
 * outbound writer + supervisor + aggregator own stdin/stdout/stderr, and a
 * `LiveSession` is registered so `send_chat_message_to_agent` can reach the
 * subprocess. Read-only adapters (codex/opencode/generic) go through
 * `spawn_raw_capture_tasks` — stdout/stderr lines become raw_stdout /
 * raw_stderr rows in agent_events.
 */
async launchAgent(agentType: string, cwd: string, intent: string | null, options: LaunchOptions | null) : Promise<Result<AgentInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_agent", { agentType, cwd, intent, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Terminate a running agent by ID.
 * 
 * T-03-06 mitigation: Only terminates processes tracked in the registry.
 * Will not kill arbitrary PIDs.
 * 
 * Phase 8 D-10 force-deny: signals every pending hook waiter for this
 * agent with `HookDecision::Deny("agent terminated by user")` BEFORE the
 * OS kill. This prevents the EPIPE race where the sidecar dies mid-read
 * and Claude hangs waiting for a response that will never come. Also
 * clears the agent's always-allow set and session bindings so a
 * reconnection doesn't resurrect stale state.
 */
async terminateAgent(agentId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminate_agent", { agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update an agent's intent/task description (manual labeling per D-08 fallback).
 */
async updateAgentIntent(agentId: string, intent: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_agent_intent", { agentId, intent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the stdout log buffer for an agent.
 * 
 * T-03-08: accepted risk -- logs are local process output.
 */
async getAgentLogs(agentId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_agent_logs", { agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Accept the passive-detected Claude hook consent prompt for `repo_cwd`:
 * records the decision in `app_settings` AND installs the AITC PreToolUse
 * hook into `<repo_cwd>/.claude/settings.local.json`.
 */
async acceptPassiveHookConsent(repoCwd: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("accept_passive_hook_consent", { repoCwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Decline the passive-detected Claude hook consent prompt for `repo_cwd`:
 * records the decision so we never re-prompt. Does NOT install the hook.
 */
async declinePassiveHookConsent(repoCwd: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("decline_passive_hook_consent", { repoCwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve the absolute path of the `aitc-hook` sidecar binary at runtime.
 * 
 * Tauri v2 stages sidecars next to the main executable with the target-triple
 * suffix stripped, so `ShellExt::sidecar("aitc-hook")` is the canonical way to
 * resolve the path (dev builds use `target/debug/aitc-hook`; bundled releases
 * use the staged copy in the app's exec dir).
 */
async resolveSidecarPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_sidecar_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Phase 18 D-04: read-only diagnostic snapshot of the agent registry.
 * 
 * Returns counts by ID-prefix (PASSIVE-*, KAGENT-*), `launched_by_aitc`
 * count, and the lifetime monotonic `capacity_hits_since_start`
 * counter. Intended for post-hoc debugging of "why did a KAGENT launch
 * fail with 'Registry at capacity'?" questions.
 * 
 * Safe to poll at any cadence — single read-lock acquisition + one
 * atomic load inside `snapshot_stats()`; does not contend with the
 * `upsert_agent` write path.
 */
async getRegistryStats() : Promise<Result<RegistryStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_registry_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: get current notification preferences.
 */
async getNotificationPrefs() : Promise<Result<NotificationPrefs, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_notification_prefs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: update notification preferences.
 */
async updateNotificationPrefs(prefs: NotificationPrefs) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_notification_prefs", { prefs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all active (non-dismissed) conflict alerts.
 */
async listConflicts() : Promise<Result<ConflictAlert[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_conflicts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismiss a conflict alert by its ID.
 */
async dismissConflict(conflictId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_conflict", { conflictId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current conflict detection window in milliseconds.
 */
async getConflictSettings() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conflict_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update the conflict detection window. Validates range: 1000-60000ms (1-60 seconds).
 * 
 * Mitigates T-03-09: prevents DoS via 0ms window (every write conflicts) or
 * effectiveness bypass via huge window.
 */
async updateConflictWindow(windowMs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_conflict_window", { windowMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all approval requests, newest first.
 */
async listApprovalRequests() : Promise<Result<ApprovalRequest[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_approval_requests") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Approve a pending request.
 * 
 * Phase 8 semantics: signals the pending /hook waiter (if any) with
 * `HookDecision::Allow`. Pitfall 8 guards via `rows_affected()` — if the row
 * already resolved (e.g. AbandonGuard flipped it to `abandoned`) we skip the
 * signal and just re-emit `approval-resolved` so the UI re-syncs.
 * 
 * `always_allow_for_session=true` inserts (agent_id, tool_name) into the
 * in-memory always-allow set so subsequent /hook calls bypass row creation
 * (D-22). The set is cleared on terminate_agent + process restart — never
 * persisted to disk.
 */
async approveRequest(id: number, alwaysAllowForSession: boolean | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("approve_request", { id, alwaysAllowForSession }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deny a pending request.
 * 
 * Phase 8 semantics: signals the pending /hook waiter with
 * `HookDecision::Deny(reason)`. `reason=None` falls back to
 * `"denied by user"`. Pitfall 8 guard: only flip and signal if the row is
 * still `pending`.
 */
async denyRequest(id: number, reason: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("deny_request", { id, reason }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Request more information on a pending request. Also creates a chat message
 * with the question so the agent sees it in the communications channel.
 */
async askMoreInfo(id: number, question: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ask_more_info", { id, question }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Approve a request with edited content.
 * 
 * Phase 8 semantics: derives a Claude-compatible `updated_input` JSON from
 * the stored `tool_input_json`, replacing the tool-specific content field
 * (`new_string` for Edit/MultiEdit, `content` for Write, `new_source` for
 * NotebookEdit) with `edited_content`. Signals the waiter with
 * `HookDecision::AllowWithEdits(updated_input)`.
 * 
 * Pitfall 8 guard: only flip + signal if the row is still `pending`.
 */
async approveWithEdits(id: number, editedContent: string, alwaysAllowForSession: boolean | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("approve_with_edits", { id, editedContent, alwaysAllowForSession }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all configured protected path glob patterns.
 */
async listProtectedPaths() : Promise<Result<ProtectedPath[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_protected_paths") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a new protected path glob pattern.
 */
async addProtectedPath(globPattern: string) : Promise<Result<ProtectedPath, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_protected_path", { globPattern }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a protected path by ID.
 */
async removeProtectedPath(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_protected_path", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: get current CPU and memory usage.
 * 
 * Reuses the System instance from managed state. The frontend's 2-second
 * polling interval provides the time delta needed for meaningful CPU
 * usage values between refresh calls.
 */
async getSystemLoad() : Promise<Result<SystemLoadInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_system_load") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read file versions for a conflict: base from git HEAD, current from disk.
 * 
 * Both agent_a_content and agent_b_content are set to the current disk content
 * since agents write to the same file -- the latest write is what's on disk.
 * The base version comes from `git show HEAD:<relative_path>`.
 * 
 * File size is capped at 1MB (T-05-04).
 */
async readConflictFiles(conflictId: string) : Promise<Result<ConflictFileVersions, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_conflict_files", { conflictId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apply a conflict resolution: backup files, write merged content, persist to DB.
 * 
 * Steps:
 * 1. Look up conflict alert
 * 2. Read current file + git base
 * 3. Save backups (base, agent_a, agent_b versions)
 * 4. Write merged_content to disk
 * 5. Save backup of merged version
 * 6. INSERT into conflict_resolutions
 * 7. UPDATE conflict_events SET resolution_id
 * 8. Dismiss the conflict alert
 * 9. Emit "conflict-resolved" event
 * 10. Return the ResolutionRecord
 */
async applyResolution(conflictId: string, mergedContent: string, hunkResolutions: HunkResolution[], resolutionType: string) : Promise<Result<ResolutionRecord, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_resolution", { conflictId, mergedContent, hunkResolutions, resolutionType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all conflict resolutions, most recent first.
 */
async listConflictResolutions() : Promise<Result<ResolutionRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_conflict_resolutions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List files touched in a given session, ordered by write count descending.
 */
async listSessionFiles(sessionId: number) : Promise<Result<SessionFileRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_session_files", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record a file write for a session (upsert pattern).
 * 
 * If the file was already recorded for this session, increments write_count.
 * Also updates the session's file_count aggregate.
 */
async recordSessionFile(sessionId: number, filePath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_session_file", { sessionId, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all agent sessions with file counts, most recent first.
 */
async listSessions() : Promise<Result<SessionRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List approval request history with agent context, most recent first.
 */
async listApprovalHistory() : Promise<Result<ApprovalHistoryRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_approval_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startClaudeResourcesWatch(cwd: string | null, channel: TAURI_CHANNEL<ResourceEventBatch>) : Promise<Result<Resource[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_claude_resources_watch", { cwd, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopClaudeResourcesWatch() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_claude_resources_watch") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readClaudeMd(path: string, cwd: string | null) : Promise<Result<ReadClaudeMdResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_claude_md", { path, cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeClaudeMd(path: string, content: string, cwd: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_claude_md", { path, content, cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendChatMessageToAgent(agentId: string, content: string) : Promise<Result<AgentEvent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_chat_message_to_agent", { agentId, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAgentEvents(agentId: string, beforeId: number | null, limit: number | null) : Promise<Result<AgentEvent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_agent_events", { agentId, beforeId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listChatChannels() : Promise<Result<ChatChannel[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_chat_channels") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAgentThread(agentId: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_agent_thread", { agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markAgentEventsRead(agentId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_agent_events_read", { agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async relaunchAgentSession(agentId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("relaunch_agent_session", { agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * A single row out of the `agent_events` table (D-14). `payload_json` holds
 * the shape keyed by `event_type` — see PATTERNS.md "payload_json shapes"
 * for the per-event schema. Stored as `serde_json::Value` on the wire so
 * specta maps it to an `unknown` TypeScript alias; the frontend switches
 * on `event_type` to narrow.
 */
export type AgentEvent = { id: number; agentId: string; sessionId: string | null; eventType: string; payloadJson: JsonValue; approvalRequestId: number | null; sequenceNumber: number | null; createdAt: string; 
/**
 * Only populated on `user_text` outbound rows. NULL otherwise per D-10.
 */
deliveryStatus: string | null }
/**
 * Metadata about an agent visible to the frontend and stored in the registry.
 */
export type AgentInfo = { id: string; agentType: string; protocol: string; state: AgentState; pid: number | null; cwd: string | null; intent: string | null }
/**
 * Agent lifecycle state machine.
 * 
 * Valid transitions (per 03-RESEARCH.md):
 * - Running -> Idle, Waiting, Conflict, Error
 * - Idle -> Running, Error
 * - Waiting -> Running, Error
 * - Conflict -> Running, Error
 * - Error -> Running
 */
export type AgentState = "running" | "idle" | "waiting" | "conflict" | "error"
/**
 * An approval request record for history display.
 */
export type ApprovalHistoryRecord = { id: number; sessionId: number | null; agentId: string | null; requestType: string; filePath: string | null; status: string; createdAt: string; resolvedAt: string | null; responseNote: string | null }
/**
 * An approval request from an agent (enriched with Phase 4 fields).
 * 
 * Phase 8 extension: `tool_name`, `tool_input_json`, `session_id` carry the
 * Claude Code PreToolUse context for pretool_use rows. These are `Option`
 * because write_access rows (Phase 4 protected-path trigger) don't have them.
 */
export type ApprovalRequest = { id: number; agentId: string; requestType: string; filePath: string | null; diffContent: string | null; status: string; urgency: string; responseNote: string | null; editedContent: string | null; createdAt: string; resolvedAt: string | null; toolName: string | null; toolInputJson: string | null; sessionId: string | null }
/**
 * Which process we believe authored the file event.
 * 
 * Per D-05/D-06 this is best-effort. `Unattributed` is the common fallback
 * when sysinfo's process snapshot couldn't find an agent whose cwd contains
 * the event's path. `Ambiguous` carries every candidate PID so the UI can
 * surface the disambiguation rather than pick wrong.
 */
export type Attribution = { kind: "pid"; value: number } | { kind: "ambiguous"; value: number[] } | { kind: "unattributed" }
export type CallShape = "literal" | "typed"
/**
 * D-01: four UI categories (Skills, Agents, Plugins, Configuration). The
 * "Configuration" UI tab bundles Hook + Command + Settings + Mcp; the
 * backend keeps them as distinct enum variants so the parser, store, and
 * detail panel can render them with the right metadata. ClaudeMd is its
 * own category — surfaced under Configuration in the rail.
 */
export type Category = "skill" | "agent" | "plugin" | "hook" | "command" | "settings" | "mcp" | "claudeMd"
/**
 * Rich master-list payload for the CHAT tab rail. Computed by
 * `list_chat_channels` — Wave 0 just declares the shape.
 */
export type ChatChannel = { agentId: string; adapterType: string; status: string; archived: boolean; chatDuplex: boolean; lastEvent: AgentEvent | null; unreadCount: number; currentSessionId: string | null }
/**
 * An alert generated when two different agents write the same file within the
 * configured conflict window.
 */
export type ConflictAlert = { id: string; filePath: string; agentAId: string; agentAPid: number; agentBId: string; agentBPid: number; detectedAtMs: number; conflictWindowMs: number; hunkHintsA: [number, number] | null; hunkHintsB: [number, number] | null; dismissed: boolean }
/**
 * File versions for a conflict: base (git HEAD), and current disk content.
 */
export type ConflictFileVersions = { baseContent: string; agentAContent: string; agentBContent: string; filePath: string; agentAId: string; agentBId: string }
/**
 * Per-row delivery-status update; emitted on the `agent-delivery-updated`
 * Tauri event as the stdin writer / MCP sink mutate outbound rows (D-10).
 */
export type DeliveryUpdate = { eventId: number; status: string }
/**
 * Wire-format for the get_dependency_graph Tauri command (D-05).
 */
export type DependencyEdgeDto = { 
/**
 * Repo-relative forward-slash path of importing file.
 */
from: string; 
/**
 * Repo-relative forward-slash path of imported file.
 */
to: string; kind: EdgeKind }
export type EdgeKind = "import" | "reexport" | "typeOnly" | "dynamicImport" | "use" | "modDecl" | "fromImport" | "importStmt" | 
/**
 * Phase 12 D-27: caller file → bridge node (frontend invoke call-site).
 */
"invokes" | 
/**
 * Phase 12 D-27: bridge node → Rust handler file.
 */
"handles"
/**
 * A single debounced, attributed filesystem event.
 */
export type FileEvent = { path: string; kind: FileEventKind; 
/**
 * Unix timestamp in milliseconds (UTC). i64 rather than u64 to match the
 * `chrono::DateTime::timestamp_millis()` return type.
 */
timestampMs: number; attribution: Attribution }
/**
 * A batch of events sent across the IPC boundary in one payload.
 * 
 * Batching amortizes the serde + Channel overhead across many events. The
 * `dropped_batches` counter is how the Rust side signals back-pressure to the
 * frontend: when the bounded tokio mpsc between the watcher and the sender
 * actor is full, whole batches are dropped and this counter increments.
 */
export type FileEventBatch = { events: FileEvent[]; batchId: number; droppedBatches: number }
/**
 * The kind of filesystem mutation observed.
 * 
 * Writes-only per D-11 — no read events. Rename carries both source and
 * destination paths so consumers don't need to correlate a separate
 * Remove+Create pair (the debouncer already does that work).
 */
export type FileEventKind = { kind: "create" } | { kind: "modify" } | { kind: "remove" } | { kind: "rename"; from: string; to: string }
/**
 * Resolution choice for a single hunk in the merge UI.
 */
export type HunkResolution = { hunkIndex: number; choice: string; customContent: string | null }
/**
 * Wire-format for the get_ipc_bridges Tauri command (D-06).
 */
export type IpcBridgeDto = { 
/**
 * camelCase name from bindings.ts (e.g. "startWatch").
 */
commandName: string; 
/**
 * snake_case Rust fn name (e.g. "start_watch").
 */
rustName: string; 
/**
 * Repo-relative forward-slash path to the Rust handler file. Empty
 * string if no handler was found (dangling command — D-09).
 */
handlerFile: string; 
/**
 * 1-indexed line number of the `fn` declaration. 0 if dangling.
 */
handlerLine: number; 
/**
 * Aggregated frontend call-sites (sorted by (file, line)).
 */
callerFiles: IpcCallSite[]; 
/**
 * Truncated "(args) → return" summary for the tooltip (≤ 200 chars).
 */
signatureSummary: string; 
/**
 * True if the command signature contains a `TAURI_CHANNEL<…>` arg.
 */
hasChannelArg: boolean }
export type IpcCallSite = { 
/**
 * Repo-relative forward-slash path of the caller file.
 */
file: string; 
/**
 * 1-indexed line number of the call-site.
 */
line: number; 
/**
 * Which call-site shape produced this hit.
 */
shape: CallShape }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Adapter-specific launch tuning. Currently only Claude Code consumes any of
 * these; other adapters ignore them. Kept as one serializable struct so the
 * IPC surface stays flat even as new options show up.
 */
export type LaunchOptions = { 
/**
 * Claude Code: adds `--permission-mode acceptEdits` so file-edit tools
 * run without prompting.
 */
acceptEdits: boolean; 
/**
 * Claude Code: adds `--dangerously-skip-permissions` which disables the
 * permission prompt entirely. Takes precedence over `accept_edits`.
 */
dangerouslySkipPermissions: boolean; 
/**
 * Phase 10: the AITC-assigned agent_id for this launch. Needed by
 * duplex adapters (claude-code) so they can write the per-session MCP
 * config to `.claude/aitc-mcp-<agent_id>.json` BEFORE spawning. Other
 * adapters ignore it. `None` means "generate inside the command layer";
 * `Some(id)` forces a specific id (used by relaunch_agent_session to
 * preserve transcript continuity for an archived agent — D-04).
 */
agentId?: string | null; 
/**
 * Phase 10: AITC self_register port (defaults to 9417). Duplex adapters
 * splice this into the MCP config URL so Claude's `--mcp-config` points
 * at the running /mcp handler.
 */
aitcPort?: number | null }
/**
 * Per-state notification preferences.
 * 
 * Each field controls whether a transition TO that state triggers a
 * native OS notification.
 */
export type NotificationPrefs = { 
/**
 * Notify when agent enters Running state. Default: false.
 */
onRunning: boolean; 
/**
 * Notify when agent enters Idle state. Default: true.
 */
onIdle: boolean; 
/**
 * Notify when agent enters Waiting state. Default: true.
 */
onWaiting: boolean; 
/**
 * Notify when agent enters Conflict state. Default: true.
 */
onConflict: boolean; 
/**
 * Notify when agent enters Error state. Default: true.
 */
onError: boolean }
/**
 * Frontend-facing process info (serializable via specta).
 * 
 * `parent_pid` is serialized as `parentPid` by the camelCase rename rule.
 */
export type ProcessInfo = { pid: number; name: string; cwd: string | null; exe: string | null; parentPid: number | null }
/**
 * A protected path glob pattern that triggers synthetic approval requests.
 */
export type ProtectedPath = { id: number; globPattern: string; createdAt: string }
/**
 * Return shape for `read_claude_md`: file content + editability flag so
 * the frontend knows whether to render a read-only preview or an editor.
 */
export type ReadClaudeMdResult = { content: string; editable: boolean; path: string }
/**
 * Read-only diagnostic snapshot of the agent registry (Phase 18 D-04).
 * 
 * Counts are derived by ID-prefix convention (`PASSIVE-*`, `KAGENT-*`);
 * `launched_count` is orthogonal and counts entries with
 * `launched_by_aitc = true`. `capacity_hits_since_start` is the lifetime
 * monotonic counter incremented on every `upsert_agent` at-capacity
 * failure since this `AgentRegistry` was constructed.
 * 
 * Intended for post-hoc debugging of "why did a launch fail with
 * 'Registry at capacity'?" questions. Safe to call at any cadence —
 * the backing `snapshot_stats()` method acquires only the read lock +
 * one atomic load (see Pitfall 7 / T-18-02).
 */
export type RegistryStats = { totalAgents: number; passiveCount: number; kagentCount: number; launchedCount: number; capacityHitsSinceStart: number }
/**
 * A persisted conflict resolution record.
 */
export type ResolutionRecord = { id: number; conflictEventId: number | null; filePath: string; agentAId: string; agentBId: string; resolutionType: string; hunkResolutions: string; notificationStatus: string; resolvedAt: string }
/**
 * A discovered Claude resource. Identity is `id` (stable across rescans);
 * `path` is informational and may change if the file moves.
 */
export type Resource = { id: ResourceId; category: Category; scope: Scope; name: string; description: string | null; path: string; metadata: ResourceMetadata }
/**
 * Channel-emitted event variants. `Added`/`Changed` carry the parsed
 * `Resource`; `Removed` carries only the id; `ExternalEdit` exists per
 * D-15 so the frontend can decide between silent refresh and the
 * "file changed on disk" banner when an editor is mounted on `path`.
 */
export type ResourceEvent = { kind: "added"; resource: Resource } | { kind: "removed"; id: ResourceId } | { kind: "changed"; resource: Resource } | { kind: "externalEdit"; path: string; mtimeMs: number }
/**
 * Batched event envelope mirrors `pipeline::events::FileEventBatch` so the
 * frontend ring-buffer pattern from Phase 2 carries over unchanged.
 */
export type ResourceEventBatch = { events: ResourceEvent[]; batchId: number; droppedBatches: number }
/**
 * Opaque stable identifier for a Resource — composed as
 * `"{scope}::{category}::{name}"` per RESEARCH.md Pattern 2 so the
 * frontend can treat it as an opaque key without parsing.
 */
export type ResourceId = string
/**
 * Per-category metadata payload. Tagged enum (`kind` discriminator) so the
 * frontend can switch on `metadata.kind` and render the right detail panel.
 */
export type ResourceMetadata = { kind: "skill"; tools: string[] | null; allowedTools: string[] | null } | { kind: "agent"; tools: string[] | null; model: string | null } | { kind: "plugin"; version: string; marketplace: string | null; installPath: string | null; installedAt: string | null; lastUpdated: string | null; gitCommitSha: string | null } | { kind: "hook"; event: string | null; matcher: string | null } | { kind: "command"; argumentHint: string | null; allowedTools: string[] | null } | { kind: "settings"; hooksCount: number; mcpServersCount: number } | { kind: "mcp"; command: string; args: string[]; envMasked: boolean } | { kind: "claudeMd"; editable: boolean; byteSize: number }
/**
 * D-02: scope tabs Global | Project | Combined. `Combined` is a UI-only
 * concept derived from the union of Global + Project — backend only emits
 * the two physical scopes.
 */
export type Scope = "global" | "project"
/**
 * Payload for `agent-session-ended` — emitted when the long-lived subprocess
 * exits (via terminate, crash, or `{type:"result"}` terminal envelope).
 */
export type SessionEndedPayload = { agentId: string; sessionId: string | null; 
/**
 * "completed" | "crashed" | "terminated" | "error"
 */
reason: string; exitCode: number | null }
/**
 * A file record within a session.
 */
export type SessionFileRecord = { id: number; sessionId: number; filePath: string; writeCount: number; lastWrittenAt: string }
/**
 * An agent session record for history display.
 */
export type SessionRecord = { id: number; agentId: string; agentType: string; status: string; startedAt: string; endedAt: string | null; fileCount: number }
/**
 * Payload for `agent-session-started` — wired in Plan 02 when the parser
 * captures the stream-json `init` envelope's `session_id`.
 */
export type SessionStartedPayload = { agentId: string; sessionId: string }
/**
 * Live system load snapshot.
 */
export type SystemLoadInfo = { cpuPercent: number; memoryPercent: number }
export type TAURI_CHANNEL<TSend> = null
/**
 * Serializable tree node for frontend consumption (VIZN-01, VIZN-05).
 */
export type TreeIndexEntry = { path: string; size: number; isDir: boolean; depth: number }
export type Worktree = { path: string; head: string | null; branch: string | null; isMain: boolean; isBare: boolean; detached: boolean; locked: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
